# This new Amazon Linux platforms will conflict with the project we have built since 
#it will look for a docker.compose.yml file to build from by default instead of a Dockerfile.
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'