# to build this file use: [specify which file to use, otehr wise default Dockerfile]
# docker build -f Dockerfile.dev .
FROM node:16-alpine3.18

# store the copied files
WORKDIR '/app'

# install dependencies with package.json
COPY package.json .
RUN npm install

#copy all the other files
COPY . . 

# start this react app 
CMD ["npm","run","start"]

# To run
# docker run -p 3000:3000 container_id